---
# This role contains common plays that will run on all nodes
- name: Install yum utils
  yum:
    name:
      - yum-utils
      - bash-completion
      - epel-release

- name: Set facts
  set_fact:
    major_version_task_file: "{{ onecloud_major_version }}.yml"

- name: Import task "{{ major_version_task_file }}"
  include_tasks: "{{ major_version_task_file }}"

- name: Turn off selinux
  selinux:
    state: disabled

- name: Gather service facts
  service_facts:

- name: Disable systemd services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  when: "item + '.service' in ansible_facts.services"
  loop:
  - firewalld
  - NetworkManager

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Load br_netfilter at boot
  copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/modules-load.d/kubernetes.conf
    content:
      br_netfilter

- name: Change sysctl setting
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward

- name: Change sysctl fs.inotify.max_user_watches
  sysctl:
    name: "fs.inotify.max_user_watches"
    value: "65536"
    state: present

- name: Change sysctl fs.inotify.max_user_instances
  sysctl:
    name: "fs.inotify.max_user_instances"
    value: "8192"
    state: present

#  https://github.com/kubernetes-retired/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml
- name: Turn off swap mount
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Turn off swap now
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Config ipvs
  copy:
    owner: root
    group: root
    mode: "0755"
    src: ipvs.modules
    dest: /etc/sysconfig/modules/ipvs.modules
- name: Load ipvs modules
  shell:
    /etc/sysconfig/modules/ipvs.modules

# docker
- block:
  - name: Install docker
    yum:
      name:
        - docker-ce-19.03.9
        - docker-ce-cli-19.03.9
        - containerd.io

  - name: Make /etc/docker dir
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root

  - name: Config docker file
    template: src=daemon.json.j2 dest=/etc/docker/daemon.json

  - name: Restart docker service
    service: name=docker state=restarted daemon_reload=yes enabled=yes
  when:
    skip_docker_config is not defined or skip_docker_config|default(false)|bool == false

# k8s packages
- name: Install k8s packages
  yum:
    name:
      - bridge-utils
      - ipvsadm
      - conntrack-tools
      - jq
      - kubelet-1.15.8-0
      - kubectl-1.15.8-0
      - kubeadm-1.15.8-0
  tags: k8s

- name: Enable kubelet
  service: name=kubelet enabled=yes
  tags: k8s

- name: Export yunion bin path in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: "export PATH=$PATH:/opt/yunion/bin"
    state: present
    create: yes
    regexp: '^export PATH=.*/opt/yunion/bin'
  when: shell is undefined or shell == 'bash'

- name: Enable yunion systemd services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
  - yunion-executor
