---
- name: Add cloud rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.4/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: Install cloud common packages
  yum:
    state: latest
    name:
      - kernel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-devel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-headers-3.10.0-1062.4.3.el7.yn20191203
      - yunion-executor-server
  when:
  - is_centos_x86 is defined
  - non_iso_mode is defined
