---
- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.6/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
  become: yes
  when:
  - is_centos_x86 is defined
  - iso_install_mode is not defined or iso_install_mode|default(false)|bool == false

- name: Install yunion common packages
  yum:
    state: latest
    name:
      - kernel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-devel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-headers-3.10.0-1062.4.3.el7.yn20191203
      - yunion-executor
  when:
  - is_centos_x86 is defined
  - iso_install_mode is not defined or iso_install_mode|default(false)|bool == false

- name: init apt cache for uos
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.6 ./" > /etc/apt/sources.list.d/yunion.list;
    curl -k https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.6/yunion.gpg-key.asc -o yunion.gpg-key.asc;
    apt-key add yunion.gpg-key.asc;
    apt-get update -y;
    rm -f yunion.gpg-key.asc;
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined
