---
- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/nightly/3.7/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
  become: yes

- name: Change nightly yunion.repo url
  shell: |
    sed -i 's|baseurl=https://iso.yunion.cn/3.7|baseurl=https://iso.yunion.cn/nightly/3.7|g' /etc/yum.repos.d/yunion.repo

- name: Install yunion common packages
  yum:
    state: latest
    name:
      - kernel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-devel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-headers-3.10.0-1160.6.1.el7.yn20201125
      - yunion-executor
  when:
  - is_centos_x86 is defined

- name: init apt cache for uos
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.7 ./" > /etc/apt/sources.list.d/yunion.list;
    curl -k https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.7/yunion.gpg-key.asc -o yunion.gpg-key.asc;
    apt-key add yunion.gpg-key.asc;
    apt-get update -y;
    rm -f yunion.gpg-key.asc;
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined