---
- name: Add cloud rpm repository {{ online_status }} {{ ansible_architecture }}
  template: src=yunion.repo.j2 dest=/etc/yum.repos.d/yunion.repo
  when:
  - is_centos_based is defined

- name: make cache
  shell: |
    yum clean all
    yum -y --disablerepo='*' --enablerepo='yunion-repo-offline' makecache
  when:
  - is_centos_based is defined
