---
- name: Add cloud rpm repository
  get_url:
    url: https://iso.yunion.cn/centos/7/3.9/{{ansible_architecture}}/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_based is defined
  - offline_deploy|default(false)|bool == false

- name: Add cloud rpm repository for Kylin
  get_url:
    url: https://iso.yunion.cn/kylin/v10/3.9/{{ansible_architecture}}/kylin-yunion.repo
    dest: /etc/yum.repos.d/kylin-yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_kylin_based|default(false)|bool == true
  - offline_deploy|default(false)|bool == false

- name: Add cloud rpm repository for Kylin
  get_url:
    url: https://iso.yunion.cn/centos/7/3.9/{{ansible_architecture}}/kylin.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_kylin_based|default(false)|bool == true
  - offline_deploy|default(false)|bool == false

- name: make cache
  shell: |
    yum clean all
    yum -y --disablerepo='*' --enablerepo='yunion*' makecache
  when:
  - is_centos_based is defined

- name: Install cloud common packages
  yum:
    state: latest
    enablerepo: "yunion*"
    disablerepo: "*"
    name:
      - kernel-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
      - kernel-devel-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
      - kernel-headers-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
  when:
  - is_centos_x86 is defined

- name: init apt cache for debian
  get_url:
    url: https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.8/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: yes
  when:
  - is_debian_based is defined

- name: apply debian sig key
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.8 ./" > /etc/apt/sources.list.d/yunion.list;
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined

- name: install libselinux-python for arm64 centos
  yum:
    name: libselinux-python
  when:
  - is_centos_aarch64 is defined

- name: Install cloud common packages for arm64
  yum:
    state: latest
    name:
      - kernel
      - yunion-executor
  when:
  - is_centos_aarch64 is defined
  - non_iso_mode is defined
