- name: define kernel regex
  set_fact: kernel_regex="el[0-9]+.yn[0-9]{8}."

- name: is yunion kernel running
  shell: |
    uname -r | grep -E "{{ kernel_regex }}"
  register: is_yunion_kernel_running
  changed_when: false
  failed_when: false
  args:
    warn: no

- name: is yunion kernel installed
  shell: |
    count=$(rpm -qa |grep kernel |grep -E "{{ kernel_regex }}" |wc -l)
    [[ "$count" -ge 3 ]]
  register: is_yunion_kernel_installed
  changed_when: false
  failed_when: false
  args:
    warn: no

- name: install yunion kernel
  shell: "sudo yum localinstall --nogpgcheck -y /opt/yunion/upgrade/rpms/packages/{kernel,perl}/*.rpm"
  args:
    warn: no
  when: is_yunion_kernel_installed.rc != 0

- name: init grub menu
  shell: |
    conf=/etc/default/grub
    if cat /proc/cmdline | grep -q cgroup.memory=nokmem; then
      echo "[PASS] Kernel is with cgroup.memory=nokmem option. "
    else
      cp -vf $conf ${conf}.bak
      sed -i -e 's#GRUB_CMDLINE_LINUX="#GRUB_CMDLINE_LINUX="cgroup.memory=nokmem #' $conf
    fi
    sudo grub2-set-default 0
    if [ -d /sys/firmware/efi ]; then
        sudo mkdir -p /boot/efi/EFI/centos
        sudo grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
        echo "grub inited with efi."
    else
        sudo grub2-mkconfig -o /boot/grub2/grub.cfg
        echo "grub inited."
    fi
  when: is_yunion_kernel_running.rc != 0

- name: Do pre-install-host setup; it should take a few minutes...
  include_role:
    name: pre-install-host
  when: availability_controlplane_as_host|default(false)|bool == true

- name: reboot system if not yunion kernel; it should take a few minutes...
  reboot:
    reboot_timeout:  900  # 15 mins
    connect_timeout: 900 # 15 mins
    msg: "rebooting host to enable yunion kernel ... please wait... "
    test_command: "uname -r | grep -qE '{{ kernel_regex }}'   "
  when: is_yunion_kernel_running.rc != 0

