- name: Install mariadb
  package:
    name: "{{ item }}"
    state: "present"
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
    - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
  - online_status == "online"
