- name: Install mariadb
  package:
    name: "{{ item }}"
    state: "present"
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
    - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL
