- name: Copy db backup script to controller
  copy:
    src: db_backup.sh
    dest: /opt/yunion/scripts/db_backup.sh
    owner: root
    group: root
    mode: 0755
  become: true

- name: add cronjob to backup db every day.
  cron:
    name: "Backup DB Daily"
    special_time: daily
    user: root
    job: "BKUP_PATH={{ backup_path}} MAX_BKUP={{ max_backups }} LIGHT_BKUP={{light_backup}} MAX_DISK_PERCENTAGE={{ max_disck_percentage }} /opt/yunion/scripts/db_backup.sh"
    cron_file: yunion_audo_db_backup
