apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-grafana-data
  namespace: onecloud
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: local-path
  volumeMode: Filesystem
