apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
  name: default-grafana
  namespace: onecloud
type: Opaque
data:
  admin-password: YWRtaW5AMTIz
  admin-user: YWRtaW4=
  ldap-toml: ""
