- name: Include utils/kernel-check tasks
  include_role:
    name: utils/kernel-check
  when:
    - k8s_node_as_oc_host|default(false)|bool == true
    - no_reboot is not defined or no_reboot|default(false)|bool == false
