---
- name: Ensure a cronjob that renews certificates
  cron:
    name: "Use kubeadm renew certificates"
    special_time: monthly
    user: root
    job: "/opt/yunion/bin/ocadm alpha certs renew all"
    cron_file: yunion_kubeadm_renew_certs
