---
- name: collect upgrade info
  import_tasks: collect_upgrade_info.yml

- name: Include utils/detect-os tasks
  include_role:
    name: utils/detect-os

- name: Include cronjobs
  include_role:
    name: utils/cronjobs

- name: common upgrade | Import major version upgrade task
  include_tasks: "{{ major_upgrade_task_file }}"
  when:
    - is_major_upgrade
