---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add yunion rpm repository {{ yunion_yum_repo }}"
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
    force: yes
  become: yes
  when:
  - is_centos_x86 is defined

- name: Upgrade yunion common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
      - kernel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-devel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-headers-3.10.0-1160.6.1.el7.yn20201125
    state: latest
  when:
  - is_centos_x86 is defined
