---

is_centos_based: true
is_kylin_arm64: true
is_kylin_based: true

common_packages:
  - bash-completion
  - boost-iostreams
  - boost-random
  - boost-system
  - boost-thread
  - bridge-utils
  - ca-certificates
  - celt051
  - ceph-common
  - conntrack-tools
  - curl
  - fuse
  - fuse-devel
  - fuse-libs
  - gssproxy
  - ipset
  - ipvsadm
  - jq
  - keyutils
  - kmod
    # - kmod-openvswitch
  - kubeadm-1.15.12-0
  - kubectl-1.15.12-0
  - kubelet-1.15.12-0
  - libbasicobjects
  - libcollection
  - libini_config
  - libjpeg-turbo
  - libnfsidmap
  - libogg
  - libpath_utils
  - libpcap
  - librados2
  - librbd1
  - libref_array
  - libtirpc
  - libusb
  - libusbx
  - libverto-libevent
  - lm_sensors-libs
  - nfs-utils
  - nmap-ncat
  - openvswitch
  - pixman
  - python2-libselinux
  - python3-libselinux
  - quota
  - quota-nls
  - rpcbind
  - sysstat
  - tcp_wrappers
  - tcpdump
  - unbound
  - unbound-libs
  - usbredir
  - wget
  - yunion-climc
  - yunion-executor
  - yunion-fetcherfs
  - yunion-ocadm
  - yunion-ovmfrpm
  - yunion-qemu-4.2.0

common_services:
    - ntpd
    - yunion-executor
