{{ $cluster := .Values.cluster }}
{{ $mysql := .Values.cluster.mysql }}
# deploy onecloud cluster customize resource instance
apiVersion: "onecloud.yunion.io/v1alpha1"
kind: OnecloudCluster
metadata:
  name: {{ include "cloudpods.fullname" . }}
  annotations:
    onecloud.yunion.io/edition: "{{ .Values.cluster.edition }}"
    helm.sh/hook: post-install
spec:
  mysql:
    host: {{ template "cloudpods.cluster.mysql.host" . }}
    port: {{ $mysql.port }}
    username: {{ $mysql.user }}
    password: {{ $mysql.password }}
  region: "region0"
  imageRepository: "{{ $cluster.imageRepository }}"
  version: "{{ $cluster.version | default .Chart.AppVersion }}"
  loadBalancerEndpoint: "{{ $cluster.publicEndpoint }}"
  disableResourceManagement: {{ $cluster.disableResourceManagement }}
  productVersion: {{ $cluster.productVersion }}
  baremetalagent:
    disable: {{ $cluster.baremetalagent.disable }}
    requests:
      storage: {{ $cluster.baremetalagent.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  glance:
    requests:
      storage: {{ $cluster.glance.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  influxdb:
    requests:
      storage: {{ $cluster.influxdb.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  meter:
    requests:
      storage: {{ $cluster.meter.requests.storage }}
    storageClassName: {{ template "cloudpods.cluster.storageClass" . }}
  onecloudServiceOperator:
    disable: true
