- name: yum install yunion HOST packages; it should take a few minutes...
  yum:
    name: "{{ packages }}"
    disablerepo: "*"
    enablerepo: "yunion-*"
  vars:
    packages:
      - boost-iostreams
      - boost-random
      - boost-system
      - boost-thread
      - celt051
      - fuse
      - fuse-devel
      - fuse-libs
      - gssproxy
      - keyutils
      - kmod
      - kmod-openvswitch
      - libbasicobjects
      - libcollection
      - libini_config
      - libjpeg-turbo
      - libnfsidmap
      - libogg
      - libpath_utils
      - libpcap
      - librados2
      - librbd1
      - libref_array
      - libtirpc
      - libusb
      - libusbx
      - libverto-libevent
      - lm_sensors-libs
      - nfs-utils
      - nmap-ncat
      - openvswitch
      - pixman
      - quota
      - quota-nls
      - rpcbind
      - spice
      - spice-protocol
      - sysstat
      - tcp_wrappers
      - tcpdump
      - unbound
      - unbound-libs
      - usbredir
      - yunion-executor-server
      - yunion-ovmfrpm
      # - openvswitch-ovn-common    # ignored
      # - openvswitch-ovn-host      # ignored

- name: init GPU
  shell: /opt/yunion/upgrade/gpu_init/gpu_sutup.sh

