- name: Install registry
  yum: name={{ item }} state=present
  with_items:
  - yunion-registry
  when:
  - is_centos_x86 is defined
  - iso_install_mode is not defined or iso_install_mode|default(false)|bool == false

- name: Config registry
  template: src=registry.yml dest=/etc/yunion/registry.yml
  notify: restart registry

- name: Start registry service
  service: name=yunion-registry state=started enabled=yes
