- name: Stop kubelet services
  service:
    name: kubelet
    state: stopped

- name: List containers of K8s
  shell: |
    docker ps | grep '\sk8s_' | awk '{print $0}'
  args:
    executable: /bin/bash
  register: k8s_containers

- name: "Stop containers of K8s"
  include_tasks: stop-container.yml
  with_items:
    "{{ k8s_containers.stdout_lines }}"
  vars:
    container_info: "{{ item }}"
