- name: test var enable_eip_man
  shell: |
    if grep -q '^sdn_enable_eip_man:' /etc/yunion/host.conf; then
      sed -i -e 's#^sdn_enable_eip_man.*#sdn_enable_eip_man: true#' /etc/yunion/host.conf
    else
      echo 'sdn_enable_eip_man: true' >> /etc/yunion/host.conf
    fi
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl rollout restart ds -n onecloud default-host
  args:
    executable: /bin/bash
  when:
  - enable_eip_man|default(false)|bool == true
