# This role contains common plays that will run on all nodes

- name: Install Cloud Kernel
  yum:
    enablerepo: "yunion*"
    disablerepo: "*"
    name:
    - kernel-5.4.223-1.yn20221106.el7
    - kernel-devel-5.4.223-1.yn20221106.el7
    - kernel-headers-5.4.223-1.yn20221106.el7
