# This role contains common plays that will run on all nodes

- name: Install Cloud Kernel
  yum:
    enablerepo: "yunion*"
    disablerepo: "*"
    name:
      - kernel-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
      - kernel-devel-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
      - kernel-headers-0:3.10.0-1160.53.1.el7.yn20220518.x86_64
