- name: add sync-user option
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    tmp=$(mktemp).yaml
    kubectl get deployment onecloud-operator -n onecloud -o yaml > $tmp
    sed -i -e '/onecloud-controller-manager$/a \        - -sync-user' $tmp
    kubectl replace -f $tmp
    rm -f $tmp
  args:
    executable: /bin/bash
  when:
  - restore_mode is defined
  - restore_mode | default(false) | bool == true
